# Info:
# - Travis CI for iOS - https://www.objc.io/issues/6-build-tools/travis-ci/
# - Travis CI Tutorial - http://www.raywenderlich.com/109418/travis-ci-tutorial
# - Building Swift Project: https://docs.travis-ci.com/user/languages/objective-c/

language: objective-c
osx_image: xcode10.1
install: gem install ffi
script: make ci

branches:
  only:
  - master
  - /^release\/.*$/
